services:
  python-service:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: python_flash_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
